name: esrgan
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.6
  - pip>=20.3
  - pip:
    - basicsr>=1.4.2
    - facexlib>=0.2.5
    - gfpgan>=1.3.5
    - numpy
    - opencv-python
    - Pillow
    - torch>=1.7
    - torchvision
    - tqdm
    - -e .
variables:
  LD_LIBRARY_PATH: /opt/conda/envs/esrgan/lib/python3.9/site-packages/nvidia/cublas/lib:/usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64