name: esrgan
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - pytorch-cuda=11.6
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - basicsr
    - facexlib
    - gfpgan
    - numpy
    - opencv-python
    - Pillow
    - torch>=1.7
    - torchvision
    - tqdm
    - -e .
